### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by mariyamh** [AppLozic/Applozic-Web-Plugin#140]
how to run the given demo

**Comment by ab14bhardwaj** [comment]
Hello @mariyamh ,

Hope you're doing well. 
Please refer to this [link](https://github.com/AppLozic/Applozic-Web-Plugin/tree/master/public/demo) and follow the instructions mentioned there to run the demo.

**Comment by mariyamh** [comment]
i found it but could nt proceed because of python. help me to run it on node.js
   On Wednesday, September 5, 2018, 12:09:00 AM PDT, Abhinav Bhardwaj <notifications@github.com> wrote:  
 
 
Hello @mariyamh ,

Hope you're doing well.
Please refer to this link and follow the instructions mentioned there to run the demo.

**Comment by mariyamh** [comment]
how to run it on node js

**Comment by ab14bhardwaj** [comment]
Hello Mariyamh, 

Steps to run it node are :  

1. Clone the latest version of Applozic-Web-Plugin repository.
2. Open terminal and come to the Applozic-Web-Plugin folder.
3. Run npm install.
4. Run node app.js

**Comment by mariyamh** [comment]
i know how to run it.but dont knw how to integrate it in my template

    On Thursday, September 13, 2018, 11:41:47 PM PDT, Abhinav Bhardwaj <notifications@github.com> wrote:  
 
 
Hello Mariyamh,

Steps to run it node are :
   
   - Clone the latest version of Applozic-Web-Plugin repository.
   - Open terminal and come to the Applozic-Web-Plugin folder.
   - Run npm install.
   - Run node app.js

**Comment by ab14bhardwaj** [comment]
Please refer to our [`web-plugin documentation`](https://docs.applozic.com/docs/web-javascript-chat-plugin), it will help you in integrating our web-plugin.
