### ISSUE TITLE
ReferenceError: IS_LOGGED_IN is not defined

### ISSUE THREAD

**Issue by pttsky** [AppLozic/Applozic-Web-Plugin#153]
Hello dear team of Applozic Web Plugin. First of all, thank you for your great and convenient chat solution and very well designed chat API.

## Goals
I am building chat UI from scratch in React, just by using Applozic API, and I want to perform user logout. I know there are several ways to do it, like `window.Applozic.ALApiService.logout({...})` then `window.Applozic.ALSocket.disconnect()` but the [docs suggests](https://docs.applozic.com/docs/web-javascript-chat-logout#section-build-your-ui-from-scratch) to use `ALCustomService` when building UI from scratch: 

## Code Sample
```
function logoutHandle(status){
  return dispatch => {
    if (window.Applozic) {
      window.Applozic.AlCustomService.logout();
    }
    dispatch({
      type: LOGOUT,
      payload: status,
    });
  };
}
```

## Expected Results
No errors

## Actual Results
I am getting error in console: `ReferenceError: IS_LOGGED_IN is not defined`

Browser: Chrome

Browser version: 69.0.3497.100 (Official Build) (64-bit)

I think this bug comes from the following line of code: 
https://github.com/AppLozic/Applozic-Web-Plugin/blob/402a65716140e544d094007927d8fd3de54a17c1/public/plugin/js/app/modules/customFunctions/applozic.custom.js#L15
It is the only line in the whole repository where global variable `IS_LOGGED_IN` occures and it seems redundant.

Thank you,

Serhii Pitetsky

**Comment by ab14bhardwaj** [comment]
Hello, 

Thanks for pointing this out, we would be fixing this issue by end of the day. 
Sorry for the inconvenience caused.

**Comment by ab14bhardwaj** [comment]
Hello @pttsky , 

I apologize for not updating you previously regarding this issue.
This issue is fixed.
