### ISSUE TITLE
autoTypeSearchEnabled : true allows user to break system with apostrophe

### ISSUE THREAD

**Issue by codemonkeynorth** [AppLozic/Applozic-Web-Plugin#162]
## Expected Results
adding a user when autoTypeSearchEnabled : true should not break system later (js fails etc)

## Actual Results
we typed **I'm Spartacus** into the search box and hit enter, this created a user in the database with an ID of **I'm Spartacus**. This then breaks any JS code that uses the ID as a # reference

`Uncaught Error: Syntax error, unrecognized expression: #mck-contact-list #li-user-I'm Spartacus`

## Steps to Reproduce
* set autoTypeSearchEnabled to true 
* launch chat window and type **I'm Spartacus** then hit enter
(this creates a user in the applozic application with ID =  **I'm Spartacus**)
* message the user
* reload site 
=> observe JS error from "recent conversations" JS code
=> observe other chat window functions no longer work due to uncaught error
* login to Applozic admin => observe user name **I'm Spartacus** in ID field 

Applozic Web SDK version: ?

Browser: Chrome

Browser version: 70.0.3538.102

**Comment by PoojaGC** [comment]
Hi Team,

We have an issue filed in this sprint, will fix this in 2 weeks, hope you have received the response via email.

**Comment by codemonkeynorth** [comment]
received, thanks for the reply
