### ISSUE TITLE
Feature Request: maxLength config parameter

### ISSUE THREAD

**Issue by codemonkeynorth** [AppLozic/Applozic-Web-Plugin#163]
## Goals
set a max length for messages in the config eg `maxLength: 1000`

## Expected Results
setting a maxLength in the config will not allow users to type (or paste) messages longer than that value

thanks

**Comment by PoojaGC** [comment]
Hi Team,

Thank you for posting the query. 

At the moment we have a limit but you can implement this at your end using the javascript and set the value as per your requirements.

Hope you have received the answer via email.

**Comment by codemonkeynorth** [comment]
received, thanks
