### ISSUE TITLE
user can search / open chat with themselves

### ISSUE THREAD

**Issue by codemonkeynorth** [AppLozic/Applozic-Web-Plugin#164]
## Goals
searching a contact should exclude the current user

## Expected Results
* if i type my own name into the search, it should exclude myself as a result
* i should not be able to open up a chat window with myself

## Actual Results
* I can search myself in the contacts list
* I can open a chat window with myself (although it says I have "blocked this user")

## Steps to Reproduce
* search your own name
* start a new chat with yourself

Applozic Web SDK version: ?

Browser: Chrome

Browser version: 70.0.3538.102

**Comment by ab14bhardwaj** [comment]
Hello @codemonkeynorth ,

To disable self chat, you can pass the parameter "disableSelfChat": true in appOptions while intializing the script [(refer this)](https://docs.applozic.com/docs/web-javascript-chat-session#section-login-register-user)

**Comment by codemonkeynorth** [comment]
fixed thanks
