### ISSUE TITLE
hitting return when editing a group name adds a newline, and shows the name as blank

### ISSUE THREAD

**Issue by codemonkeynorth** [AppLozic/Applozic-Web-Plugin#165]
## Goals
should be able to edit a group name and hit return (without it then showing the group name as blank due to newline)

## Expected Results
when I hit return and save it should not show the group name as blank

## Actual Results
when i hit return and then save, the group name shows as blank since the last line is blank

## Steps to Reproduce
* add a group
* edit group name
* hit return
=> observe blank line is added
* hit tick to save group name
=> observe group name shows as blank, since it's showing the last empty line.

Applozic Web SDK version: ?

Browser: Chrome

Browser version: 70.0.3538.102

**Comment by codemonkeynorth** [comment]
![group-name-multiline](https://user-images.githubusercontent.com/20189985/48770346-e204c800-ecb5-11e8-9137-b9a09b4e93be.JPG)

![group-name-multiline-blank](https://user-images.githubusercontent.com/20189985/48770377-fa74e280-ecb5-11e8-85fa-3eaf6755feb2.JPG)

**Comment by ab14bhardwaj** [comment]
@codemonkeynorth We were unable to reproduce this issue and everything was working fine. You might be using an older version of applozic web repository code. Can you update and check once.

**Comment by codemonkeynorth** [comment]
you need to add the group, save it - then later go back to edit it the group name and then add the extra line with enter key

* if you're just adding the group hitting enter saves it...  (not a problem here)
* but if you're editing the group, hitting enter adds a new blank line which is shown when hitting save.

I will check the code versions though

**Comment by priyadarshi** [comment]
@codemonkeynorth  We are unable to reproduce this issue with latest code. Please let us know if you are still facing this issue.
