### ISSUE TITLE
 if you create a group, add a message and exit.. it doesn't show on your list until page refresh

### ISSUE THREAD

**Issue by steoneill** [AppLozic/Applozic-Web-Plugin#171]
## Goals
Real time group conversation update.

## Expected Results
Once a group is added, it should show in the contact list immediately.

## Actual Results
if you create a group, add a message and exit.. it doesn't appear on your list until page refresh

## Steps to Reproduce
> messaging > create group > back > add message > back to list .. group does not show> refresh page > messaging > group shows

Applozic Web SDK version: ?
unsure

Browser: Chrome

Browser version: 60

**Comment by priyadarshi** [comment]
@steoneill 

We are unable to reproduce this issue. Can you please check it once again and let us know if you face same issue
