### ISSUE TITLE
clicking a notification opens chat but doesn't scroll down to latest message

### ISSUE THREAD

**Issue by steoneill** [AppLozic/Applozic-Web-Plugin#172]
## Goals
Real time group conversation update.

## Expected Results
When notification clicked, it should go to most recent message

## Actual Results
Opens messages at last active poiint

## Steps to Reproduce
when I open a chat window normally from contact list it scrolls down to latest message

when i click on a notification of a message (top right of browser) it doesn't scroll down to the message in the chat window

Applozic Web SDK version: ?
unsure

Browser: Chrome

Browser version: 60

**Comment by priyadarshi** [comment]
@steoneill We will fix this issue in upcoming release and let you know

**Comment by priyadarshi** [comment]
@steoneill We have this issue. Please check and let us know if you face any issue
