### ISSUE TITLE
window.Applozic.ALApiService.sendAttachment({

### ISSUE THREAD

**Issue by TEMGIT** [AppLozic/Applozic-Web-Plugin#210]
when use window.Applozic.ALApiService.sendAttachment({

the success event never fire.

 var message = {
    "type": 5,
    "message": "",
    "to": userId,        //optional, remove it if sending group message
    "groupId": groupId,  //optional, remove it if sending 1-1 message
    "metadata": {},
    "source": 1
};
window.Applozic.ALApiService.sendAttachment({
    data: {
        file: file,
        messagePxy: message
    },
    success: function (result) { },
    error: function () { }
});

**Comment by jacobkx** [comment]
Same issues with this. 

'sendMessage' is working just fine, but 'sendAttachment' is failing to give any success or error after request. The attachment is sending though, as I do get a separate 'onMessageSent' trigger, and the file shows on the Applozic dashbaord.

**Comment by ab14bhardwaj** [comment]
@TEMGIT @jacobkx This issue is fixed now.
