### ISSUE TITLE
How to display the message on the panel in a timely manner, and whether there is an API for generating the message ID on the web side

### ISSUE THREAD

**Issue by Bangser-Fx** [AppLozic/Applozic-Web-Plugin#419]
I built the UI from scratch: when sending a message, I want to immediately display it on the message panel (Applozic.ALApiService.sendMessage is not timely, such as sending an attachment message), and update the status of the message in real time (send successfully, send failed, send Medium), but I am not sure how to bind the successfully sent callback response to the message being sent, because there is no corresponding message id, how can I do it?

**Comment by Kusum-Dhoundiyal** [comment]
1) **You can refer** [Send Message doc](https://docs.applozic.com/docs/web-javascript-1-1-user-chat-and-group-chat#send-message-from-logged-in-user-to-another-user) . In send message success callback you will get msg createdAtTime and messageKey. In success callback you can write your logic to display message in message pannel.

2) **For attachment message refer** [Send Attachment doc](https://docs.applozic.com/docs/web-javascript-1-1-user-chat-and-group-chat#send-attachment)

3) **For Real Time Update refer** [Real Time update on message Receive](https://docs.applozic.com/docs/web-javascript-1-1-user-chat-and-group-chat#receive-message)

   Please follow above doc if you still face any issue please inform us.
