### ISSUE TITLE
New conversation initiation is not happening

### ISSUE THREAD

**Issue by sarojbiswal** [AppLozic/Applozic-Web-Plugin#46]
After clicking on new message button, enter the username and hit enter. The conversation is not getting started.

**Comment by devashishmamgain** [comment]
@sarojbiswal any error you are getting in developer console?

**Comment by sarojbiswal** [comment]
I getting one warning in web console as follows.

Relative positioning of table rows and row groups is now supported. This site may need to be updated because it may depend on this feature having no effect.
	
...},n.prototype.checkScrollbar=function(){this.bodyIsOverflowing=document.body.scr...

mck-ui-....min.js (line 1, col 16446)

![capture](https://cloud.githubusercontent.com/assets/17569004/14420401/867675b2-ffe9-11e5-9966-6e34d76bbe3c.PNG)

**Comment by devashishmamgain** [comment]
@sarojbiswal This is because of a cross origin request, is there any chance that you are opening the html file directly into browser? Can you try running the file under a server?

**Comment by sarojbiswal** [comment]
Devashish, Same issue is there even after deploying in container.

**Comment by devashishmamgain** [comment]
thanks @sarojbiswal for the info, @shanki091 please check this once.

**Comment by shanki091** [comment]
@sarojbiswal  @devashishmamgain  issue resolved - implemented auto suggest plugin, you can search user by name or id.
In case user not found - you can type userId and press enter to initiate chat with user.

**Comment by sarojbiswal** [comment]
This issue is resolved
