### ISSUE TITLE
Contact list display and search by userid/username is not happening

### ISSUE THREAD

**Issue by sarojbiswal** [AppLozic/Applozic-Web-Plugin#47]
After adding the contacts as json, contact list is not displaying and the search is also not happening by either userid or username. I have attached the sample code as well
[chat.txt](https://github.com/AppLozic/Applozic-Web-Plugin/files/212485/chat.txt)

**Comment by shanki091** [comment]
@sarojbiswal  you can load contacts on plugin initialize by calling 'loadContacts' function by passing contacts json. For sample code and json format  please go through plugin documentation step 8 , here is the link - https://www.applozic.com/developers.html#applozic-web-plugin-getting-started

**Comment by sarojbiswal** [comment]
This issue is resolved

**Comment by safaldas** [comment]
If I load the contacts using 
```$applozic.fn.applozic('loadContacts', {
                  contacts: contactsJSON
                });``` 
function.Will the list in the sidebox list even those contacts I have not done a chat with them.

**Comment by devashishmamgain** [comment]
@safaldas using loadContacts will only show contacts that you will be passing.

**Comment by safaldas** [comment]
![contacts list](https://user-images.githubusercontent.com/9291829/42376048-5d835ab4-813b-11e8-9c1a-b79fc453f774.png)
in this image when search for the user I get the user but it is not by default in the list that is already there only two groups I created is listed

**Comment by devashishmamgain** [comment]
can you check if the user: Rakesh is present as a member in any of the groups?
