### ISSUE TITLE
Searching for an unavailable user (or a garbage value) and hitting search opens a new chat

### ISSUE THREAD

**Issue by aswinramakrish** [AppLozic/Applozic-Web-Plugin#57]
Hi,

When you try to go to "New Conversation" -> Search for some random person (Something like "asdfasdf") and hit the Search icon, it opens a new chat interface.

Is there a resolution for this?

**Comment by devashishmamgain** [comment]
Hi @aswinramakrish,
try setting " autoTypeSearchEnabled:false" in init function.

**Comment by devashishmamgain** [comment]
Closing issue.
@aswinramakrish please reopen if its not resolved.
