### ISSUE TITLE
messages and groups missing in dashboard?

### ISSUE THREAD

**Issue by JohnnyTwoShoes** [AppLozic/Applozic-Web-Plugin#59]
hi,

I logged on this morning, and the messages and groups have gone , ie I cannot see anything in the dashboard. my user is ih300.

**Comment by devashishmamgain** [comment]
Hi, there is some issue at our side, we are releasing the new dashboard version in next 20 mins.

**Comment by devashishmamgain** [comment]
Issue is fixed, can you check it now.
