### ISSUE TITLE
React.js Integration

### ISSUE THREAD

**Issue by scottwooden** [AppLozic/Applozic-Web-Plugin#65]
Does any have any issues / tips to integrate the applozic library into a react component? Essentially we're modifying the UI to fit our layout, and we want to access the applozic functions to trigger custom messages etc. However, we can't seem to access these functions even when all the files are required. Anyone dealt with a similar issue?

**Comment by skapatech** [comment]
Just wondering if there is an update or response on this.  We're considering using applozic for a React based web app.  Thanks.

**Comment by ab14bhardwaj** [comment]
For the above mentioned issue, you can try : 
1. [React-JS-Chat](https://github.com/AppLozic/React-JS-Chat)
2. [Custom-UI ](https://docs.applozic.com/docs/web-javascript-chat-plugin)

**Comment by Faizahmadfaiz** [comment]
In React-JS-Chat https://github.com/AppLozic/React-JS-Chat#to-integrate-applozic-chat-in-your-project, the second pint is - 
**Copy applozic.html (/React-JS-Chat/public/applozic) code and add it to your header or footer(Which is common to all your code).**
I can't find any applozic.html (/React-JS-Chat/public/applozic) there.
Can any one clarify this? Thanks!

**Comment by ab14bhardwaj** [comment]
Hello @Faizahmadfaiz , 

I apologize as readme for React-JS-Chat repo might not be updated.
You find the HTML file for fullview source code [here](https://github.com/AppLozic/React-JS-Chat/blob/master/public/applozic/sample/fullview.html).

**Comment by Faizahmadfaiz** [comment]
Thanks @ab14bhardwaj for a quick response! :)
Am I supposed to add this whole html code inside my React code?
There are lot of javascript code inside script tag which is creating problem (syntax error).
I am not sure whether I am doing it the right way. Can you please tell me (any example), how to use **fullview.html** inside render in React.
Thanks!
