### ISSUE TITLE
Error in channel notification. Whoops! Lost connection to https://apps.applozic.com:15675/stomp

### ISSUE THREAD

**Issue by lequoctrung** [AppLozic/Applozic-Web-Plugin#69]
I got this error message when init Applozic Web Plugin.
I follow this document: https://www.applozic.com/docs/web-chat-plugin.html#step-1-add-plugin
Please help me fix it. Thank you!

**Comment by devashishmamgain** [comment]
@lequoctrung you must have opened the files directly from the file system. Due to security issues, socket connection doesn't work. Try running the files from the server, it will work.
