### ISSUE TITLE
loading chats for dynamically created dom elements

### ISSUE THREAD

**Issue by adeodevs** [AppLozic/Applozic-Web-Plugin#72]
I am having an issue when trying to use Applozic after my ajax calls. I load user information from the server and I'm trying to create the dom elements and load the tab acording to the web documentation for fullview. Is there a way of doing this?

**Comment by devashishmamgain** [comment]
Try the following:
- Put the html part of the full view plugin in a separate file.
- After your ajax calls are over, call the html page having the full view plugin html code and append the html into the tab or element where you want to put it.
- Move the Applozic plugin init call into a function something like loginToChat(userId, password, username) and pass the user's details to this function :
function loginToChat(userId, password, username) {
....
... applozic.init code as mentioned in documentation.
....
}

**Comment by adeodevs** [comment]
yes, this will work but the problem is, I know i dont have to login all the time (just once). The chat plugin is used at different areas on the page. in case 1, I'll use it to chat with a group of people i just obtained from ajax. In case 2, i will be the one receiving the chat from another user. If i follow the above solution, i will never receive a chat until i have initialized the plugin.

**Comment by devashishmamgain** [comment]
If you want the chat to be active whether its sending or receiving, then plugin must be initialized.
Now, the question is when to make the chat visible, that depends on your use case and application design. All you have to do is initialize the chat plugin and show/hide the view based on your layout.

**Comment by adeodevs** [comment]
I have two different UI designs on a single page application. The two have
very different functions and do not interact with each other. Yes the
plugin will need to be initialized first at startup. If the views were in
the same layout, (in this case a bootstrap modal), that would have worked
as I will just switch visibility classes but here is the case, specific ids
are used in the applozic fullview js file.
Kindly find below the illustration. What Will be the best way to approach
this?

===Modal A===
Applozic chat with customers(I'm the company)
===Modal A===
                    \
***PLUGIN INITIALIZED***
                   /
===Modal B====
Applozic chat with a company (I'm the user)
===Modal B====


On 4 Jun 2017 19:00, "Devashish Datt Mamgain" <notifications@github.com>
wrote:

If you want the chat to be active whether its sending or receiving, then
plugin must be initialized.
Now, the question is when to make the chat visible, that depends on your
use case and application design. All you have to do is initialize the chat
plugin and show/hide the view based on your layout.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AppLozic/Applozic-Web-Plugin/issues/72#issuecomment-306059800>,
or mute the thread

**Comment by devashishmamgain** [comment]
so you want a way to switch chat accounts within a single page, is that right?

**Comment by adeodevs** [comment]
Yes, switching but without ignoring the fact that you don't know when modal
A will be used and when modal B will be used so they both must be ready.
I'll only make sure that when modal A is busy modal B can't be reached and
vice versa.

**Comment by devashishmamgain** [comment]
got it, thanks for the details.
This is going to take some time to prioritize and work on it, whats your timeline for release?
If you are in hurry then lets connect on Skype: applozicinc sometime tomorrow to better understand the flow and timelines.

**Comment by adeodevs** [comment]
Okay. Let's communicate via Skype tomorrow then as we are behind schedule.

On 4 Jun 2017 19:47, "Devashish Datt Mamgain" <notifications@github.com>
wrote:

got it, thanks for the details.
This is going to take some time to prioritize and work on it, whats your
timeline for release?
If you are in hurry then lets connect on Skype: applozicinc sometime
tomorrow to better understand the flow and timelines.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AppLozic/Applozic-Web-Plugin/issues/72#issuecomment-306062595>,
or mute the thread

**Comment by devashishmamgain** [comment]
please choose a time slot that works for you: https://calendly.com/devashish-applozic
