### ISSUE TITLE
.fade.in background transparency overrules other CSS

### ISSUE THREAD

**Issue by harryo** [AppLozic/Applozic-Web-Plugin#97]
Setting `background: transparent !important;` for `.fade.in` overrules with other CSS, e.g. bootstrap popovers. Change selector to `.mck-box.fade.in`?

https://github.com/AppLozic/Applozic-Web-Plugin/blob/master/src/css/app/sidebox/applozic.sidebox.css#L575

**Comment by ab14bhardwaj** [comment]
Thanks for pointing it out, we have fixed this issue, here is the link to the code commit, please check and let us know if any further changes are required.

[https://github.com/AppLozic/Applozic-Web-Plugin/commit/f80ad77eb815527263485748b25b19e5f6a58e08](url)

**Comment by ab14bhardwaj** [comment]
Thanks for pointing it out, we have fixed this issue, here is the link to the code commit, please check and let us know if any further changes are required.

[https://github.com/AppLozic/Applozic-Web-Plugin/commit/f80ad77eb815527263485748b25b19e5f6a58e08](url)

**Comment by ab14bhardwaj** [comment]
Thanks for pointing it out, we have fixed this issue, here is the link to the code commit, please check and let us know if any further changes are required

[commit](https://github.com/AppLozic/Applozic-Web-Plugin/commit/f80ad77eb815527263485748b25b19e5f6a58e08)
